### ISSUE TITLE
Cant find picamera module

### ISSUE THREAD

**Issue by ghost** [projectweekend/Pi-Camera-Time-Lapse#1]
Installation Completed, but still getting this error.

(env)pi@raspberrypi ~/Pi-Camera-Time-Lapse $ sudo python time_lapse.py
Traceback (most recent call last):
  File "time_lapse.py", line 3, in <module>
    from camera import ConfigurableCamera
  File "/home/pi/Pi-Camera-Time-Lapse/camera/**init**.py", line 1, in <module>
    from .camera import ConfigurableCamera
  File "/home/pi/Pi-Camera-Time-Lapse/camera/camera.py", line 2, in <module>
    from picamera import PiCamera
ImportError: No module named picamera

**Comment by projectweekend** [comment]
Hey! Thanks for logging the feedback. If you plan to run the time lapse script manually, then don't run it with `sudo`. The Python dependencies that are installed by the script don't get installed with `sudo`. 

If you're not trying to run it manually, let me know and I will investigate further.
