### ISSUE TITLE
Missing the job_timelapse.yml file

### ISSUE THREAD

**Issue by subsoniq** [projectweekend/Pi-Camera-Time-Lapse#2]
Hi, and thank you for sharing this project. This is definitely an exciting project to experiment with and i have gone through the installation in the readme. Unfortunately i am a newbie and i am having trouble creating a yml file. Could you share an example yml file along with the rest of the project or do a walkthrough in the readme on how to create one?

**Comment by subsoniq** [comment]
Also, a nice twist would be to be able to upload new job files trough the dropbox connection from another pc to trigger new jobs remotely!

**Comment by projectweekend** [comment]
Hey! Thanks for the feedback. I will work up an example yml file tonight after work. Also, love the job upload idea!

**Comment by subsoniq** [comment]
Great! Thank you. Looks like i got it working now. Just copypasted the text from readme into a notepad txt and renamed it .yml 
Do you know how i can render the images into a video before uploading it to dropbox?
