### ISSUE TITLE
Is there a way of adding timestamp to the file names?

### ISSUE THREAD

**Issue by risto1913** [projectweekend/Pi-Camera-Time-Lapse#3]
I would like to use this over a period of 2 years. Take pictures during daytime.
So my thought is to set up a cronjob  to copy the YAML file every morning. And take pictures during daytime.

The issue then is that the filenames will be the same every day.

The setup is excellent!!!
Thank you for sharing.

---

never mind I added it in the time_lapse.py file :)

**Comment by projectweekend** [comment]
Nice! Glad it's worked out for you. Let me know if you need anything else.
